name: "Tests"
on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test:unit
      - name: Run Spec Tests
        run: npm run test:specs

  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Pack
        run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: marked-tgz
          path: marked-*.tgz
